services:
  ###########################################################
  # Redis message broker                                    #
  ###########################################################
  redis:
    image: redis:7-alpine
    container_name: redis-camera
    ports:
      - "6379:6379"
    volumes:
      - ./logs/redis:/var/log/redis
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - camera-network
    restart: unless-stopped
  ###########################################################
  # Express web server - stream receiver                    #
  ###########################################################
  stream-receiver:
    image: benten559/stream-receiver:latest
    container_name: stream-receiver
    # user: root # Dev container, to install debug tools inside
    ports:
      - "5000:5000"
    volumes:
      - ${DATA_PATH:-./local_data}:/data 
      # - .:/app              # Dev container, propogate changes
      # - /app/node_modules   # Dev container , use existing modules
    environment:
      - NODE_ENV=production #development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL_PATTERN=camera_stream:*
      - SERVER_PORT=5000
      - FRAME_SAVE_PATH=/data/frames
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - camera-network
    #############################
    # Comment these below DEV   #
    #############################
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/camera/available"]
      interval: 30s
      timeout: 3s
      retries: 3
    #############################
    # DEBUG OPTIONS             #
    #############################
    # Also: env for NODE_ENV ^  #
    #   BIND volumes            #
    #############################
    # restart: "no"
    # tty: true
    # stdin_open: true
    # command: tail -f /dev/null
    # healthcheck:
    #   disable: true
    #############################

  ###########################################################
  # Python camera producer                                  #
  ###########################################################
  # Publishes the Redis stream with key "raspberrypi"       #
  # Needs to access host HW devices from container          #
  # This also means that it needs privledged context        #
  # Requires the Redis server to be on and in good state    #
  ###########################################################
  camera-producer:
    image: benten559/camera-producer:latest
    container_name: camera-producer
    profiles: ["pi"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CAMERA_ID=raspberrypi
      - WIDTH=4056
      - HEIGHT=3040
      - L_WIDTH=1024
      - L_HEIGHT=768
      - ROT=90
      - FPS=30
      - JPEG_QUALITY=85
    depends_on:
      redis:
        condition: service_healthy
    privileged: true
    devices:
      - /dev/video0:/dev/video0
      - "/dev/media0:/dev/media0"
      - "/dev/media1:/dev/media1" # Access to the ISP/Unicam pipeline
      - "/dev/dma_heap/system:/dev/dma_heap/system"
      - "/dev/dma_heap/linux,cma:/dev/dma_heap/linux,cma"
    networks:
      - camera-network
    volumes:
      - "/run/udev:/run/udev:ro" # For libcamera device discovery
    #############################
    # DEBUG OPTIONS             #
    #############################
    #   - ../Stream4Pi:/app
    # tty: true
    # stdin_open: true
    # restart: unless-stopped #no
    # command: tail -f /dev/null #dummy cmd
    #############################
networks:
  camera-network:
    driver: bridge
